"""lecto_2_0_updates

Revision ID: 8b72872370e4
Revises: 001_initial
Create Date: 2025-12-28 23:23:58.483044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b72872370e4'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('original_content', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('importance_reason', sa.Text(), nullable=True),
    sa.Column('academic_link', sa.String(length=500), nullable=True),
    sa.Column('field_of_study', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('detailed_content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_ai_outputs_material_id'), table_name='ai_outputs')
    op.drop_constraint(op.f('uq_material_format'), 'ai_outputs', type_='unique')
    op.drop_index(op.f('ix_folders_user_id'), table_name='folders')
    op.create_index(op.f('ix_folders_is_group'), 'folders', ['is_group'], unique=False)
    op.drop_constraint(op.f('fk_folders_user'), 'folders', type_='foreignkey')
    op.drop_constraint(op.f('fk_folders_parent'), 'folders', type_='foreignkey')
    op.create_foreign_key(None, 'folders', 'folders', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'folders', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_group_members_group_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_user_id'), table_name='group_members')
    op.drop_index(op.f('ix_materials_folder_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_user_id'), table_name='materials')
    op.create_foreign_key(None, 'materials', 'folders', ['group_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_quiz_results_group_id'), table_name='quiz_results')
    op.drop_index(op.f('ix_quiz_results_material_id'), table_name='quiz_results')
    op.drop_index(op.f('ix_quiz_results_user_id'), table_name='quiz_results')
    op.drop_index(op.f('ix_text_chunks_material_id'), table_name='text_chunks')
    op.add_column('users', sa.Column('field_of_study', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('region', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('preferred_language', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('intellect_points', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('total_debates', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('debates_won', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('quizzes_completed', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('perfect_quizzes', sa.Integer(), nullable=True))
    op.alter_column('users', 'referral_code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.create_unique_constraint(None, 'users', ['referral_code'])
    op.drop_constraint(op.f('fk_users_referred_by'), 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_users_referred_by'), 'users', 'users', ['referred_by_id'], ['id'])
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.alter_column('users', 'referral_code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('users', 'perfect_quizzes')
    op.drop_column('users', 'quizzes_completed')
    op.drop_column('users', 'debates_won')
    op.drop_column('users', 'total_debates')
    op.drop_column('users', 'intellect_points')
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'region')
    op.drop_column('users', 'field_of_study')
    op.create_index(op.f('ix_text_chunks_material_id'), 'text_chunks', ['material_id'], unique=False)
    op.create_index(op.f('ix_quiz_results_user_id'), 'quiz_results', ['user_id'], unique=False)
    op.create_index(op.f('ix_quiz_results_material_id'), 'quiz_results', ['material_id'], unique=False)
    op.create_index(op.f('ix_quiz_results_group_id'), 'quiz_results', ['group_id'], unique=False)
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.create_index(op.f('ix_materials_user_id'), 'materials', ['user_id'], unique=False)
    op.create_index(op.f('ix_materials_folder_id'), 'materials', ['folder_id'], unique=False)
    op.create_index(op.f('ix_group_members_user_id'), 'group_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_group_members_group_id'), 'group_members', ['group_id'], unique=False)
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_folders_parent'), 'folders', 'folders', ['parent_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_folders_user'), 'folders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_folders_is_group'), table_name='folders')
    op.create_index(op.f('ix_folders_user_id'), 'folders', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_material_format'), 'ai_outputs', ['material_id', 'format'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_ai_outputs_material_id'), 'ai_outputs', ['material_id'], unique=False)
    op.drop_table('insights')
    # ### end Alembic commands ###
